CREATE TABLE IF NOT EXISTS CURSO (
    IDEN INT NOT NULL,
    ANO INT NOT NULL ,
    NOME VARCHAR(50) NOT NULL,
    PRIMARY KEY (IDEN)
);

CREATE TABLE IF NOT EXISTS DISCIPLINA(
    NOME VARCHAR(50) NOT NULL,
    CH INT NOT NULL,
    IDEN_CURSO INT,
    PRIMARY KEY (NOME),
    FOREIGN KEY (IDEN_CURSO) REFERENCES CURSO(IDEN)
)
